
version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: paintshare

  backend:
    depends_on:
      - "db"
    links:
      - "db"
    image: mathisburger/paintshare:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      DATABASE_URL: mysql://root:password@db:3306/paintshare
      RUST_LOG: ERROR
      HMAC_SECRET: secret
    volumes:
      - paintshare-data:/app/build
volumes:
  db_data: {}
  paintshare-data:
    external: true